### ISSUE TITLE
Erorr: CustomCatalogFactory not found

### ISSUE THREAD

**Issue by zonky2** [timgatzky/pct_customelements_attribute_gallery#3]
`Fatal error: Class 'PCT\CustomElements\Plugins\CustomCatalog\Core\CustomCatalogFactory' not found in /usr/www/users/xyz/contao/system/modules/pct_customelements_attribute_gallery/PCT/CustomElements/Attributes/Gallery/Gallery.php on line 285`

**Comment by timgatzky** [comment]
added integrity check: 7ff46a65e7fb56500de92e599f0de0ae06fb1200

**Comment by zonky2** [comment]
habe die `Gallery.php` ausgetauscht - nun

`Fatal error: Class 'PCT\CustomElements\Plugins\CustomCatalog\Core\CustomCatalogFactory' not found in /usr/www/users/xyz/contao/system/modules/pct_customelements_attribute_gallery/PCT/CustomElements/Attributes/Gallery/Gallery.php on line 211`

**Comment by timgatzky** [comment]
jetzt isses an allen CC stellen drin. Hab das Release geupdated
