### ISSUE TITLE
FR: Templatevariablen in Readme

### ISSUE THREAD

**Issue by zonky2** [timgatzky/pct_customelements_attribute_gallery#4]
Templatevariablen in Readme aufführen

**Comment by timgatzky** [comment]
Schau mal hier:
http://forum.premium-contao-themes.com/forum/customelements-vorlagen-pool-aa/758-customelements-und-customcatalog-template-variablen

Zusätzlich gilt überall Contaos showTemplateVars Methode.
http://de.contaowiki.org/Template_Variablen_anzeigen
